services:
  hierarchy:
    build: .
    restart: always
    container_name: hierarchy
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    command: 'npm run start'
    logging:
      options:
        max-size: '10M'
    depends_on:
      - postgres
    networks:
      - hierarchical_network

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hierarchical_network

networks:
  hierarchical_network:
    external: true

volumes:
  postgres_data:
