services:
  hierarchichy:
    build: .
    restart: always
    container_name: hierarchichy
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    command: 'npm run start'
    logging:
      options:
        max-size: '10M'
    depends_on:
      - postgres
    networks:
      - hierarchical_network

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - hierarchical_network

networks:
  hierarchical_network:
    external: true
